import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import BottomBar from "../components/navbars/BottomBar";
import Topbar from "../components/navbars/Topbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko-KR">
      <body className={inter.className}>
        <Topbar />
        <div className="main-content-container">
          <main className="main-content">{children}</main>
        </div>
        <BottomBar />
      </body>
    </html>
  );
}
